### PR TITLE
Various updates to Impact Radius, Aff Future, Aff Window and Webgains

### PR DESCRIPTION
**Pull request by slawn**
All details described in commits

### CODE REVIEW

**Review by PaoloNardini — DISMISSED** [review]
Thank you for fixing this

**Review by PaoloNardini — APPROVED** [review]

**Review by PaoloNardini — APPROVED** [review]

**Review by PaoloNardini — APPROVED** [review]
Need to maintain also env variable for back compatibility
I have merged both the options

**Review by PaoloNardini — APPROVED** [review]
Approved!

**Review by PaoloNardini — APPROVED** [review]
Approved

**Review by PaoloNardini — APPROVED** [review]
Thank you for your fix. I confirm that fake login no longer works.

**Comment by PaoloNardini** [comment]
Your changes have been manually merged because needs some small adaptions.
Please, in the future, submit only single commit pull-requests instead of a single pull-request with more commits.

**Comment by PaoloNardini** [comment]
Merged in version 2.5.9

**Comment by slawn** [comment]
> 
> 
> Your changes have been manually merged because needs some small adaptions.
> Please, in the future, submit only single commit pull-requests instead of a single pull-request with more commits.

sure no problem.

**Comment by slawn** [comment]
HI. I can see that in the Aff Window you removed status DELETED. There are 4 statuses for Aff Window: http://wiki.awin.com/index.php/API_get_transactions_list - and DELETED is like DECLINED - can we put OR condition in there as - if it's DECLINED OR DELETED - then it is DECLINED in Oara? Thanks

**Pull request closed without merging**
